---
title: "sentiment_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(fs)
library(scales)
library(lubridate)
library(dplyr)
library(knitr)
library(tibble)
library(foreign)
library(kableExtra)
library(formattable)
library(readxl)
library(readr)
library(janitor)
library(tibble)
library(purrr)
library(ggplot2)
library(ggrepel)
library(tidytext)

offender_data <- read_excel("offender_data/offender_2014-18.xlsx") %>% 
  clean_names() %>% 
  mutate(full_name = paste(first_name, last_name, sep = " ")) %>% 
  select(-last_name, -first_name)

write_rds(offender_data, "death_row_app/last_words.rds")

execution_database <- read_excel("offender_data/all_execution_database.xlsx") %>% 
  clean_names() 
  

state_executions <- execution_database %>% 
  mutate(date = ymd(date)) %>% 
  mutate(date = floor_date(date, unit = "12 months"))
  #mutate(year = as.numeric(format(date,'%Y')))


write_rds(state_executions, "death_row_app/state_executions.rds")

clean_data <- offender_data %>% 
  unnest_tokens(word, last_words)

word_cloud <- clean_data %>% 
  inner_join(get_sentiments("nrc")) %>% 
  select(word) 

word_freq <- data.frame(table(word_cloud$word)) 

write_rds(word_freq, "death_row_app/word_freq.rds")

row_exec <- read_excel("offender_data/row_exec.xlsx") %>%  
  ggplot()
write_rds(row_exec, "death_row_app/row_exec.rds")
  

totals <- clean_data %>% 
  count(full_name) %>%
  # Rename the new column
  rename(total_words = n)

word_counts <- clean_data %>% 
  left_join(totals, by = "full_name")

add_later <- offender_data %>% 
  select(-last_words)


nrc <- get_sentiments("nrc")
afinn <- get_sentiments("afinn")
bing <- get_sentiments("bing")

```
NRC analysis of positive/negative range of words
* can enable filtering based on race, sentiment
```{r}
# word_nrc <- word_counts %>% 
#   inner_join(get_sentiments("nrc")) %>% 
#   count(full_name, sentiment, total_words) %>%
#   #count(full_name, sentiment, sort = TRUE)
#   ungroup() %>%
#   # Make a new percent column with mutate 
#   mutate(percent = n/total_words) %>% 
#   filter(sentiment == "negative") %>% 
#   right_join(add_later, by = "full_name") %>% 
#   #filter(offender_race == "Hispanic") %>% 
#   filter(!is.na(sentiment)) %>% 
#   mutate(date = ymd(date)) %>% 
#   ggplot(aes(x = date, y = percent, color = total_words)) +
#     geom_line()
# 
# word_nrc
```


Most Common Words
```{r}

top_words <- word_counts %>%
  inner_join(get_sentiments("nrc")) %>%
  count(word, sentiment) %>% 
  # Group by sentiment
  group_by(sentiment) %>%
  # Take the top 10 for each sentiment
  #top_n(10) %>%
  ungroup() %>%
  # Make word a factor in order of n
  mutate(word = reorder(word, n))

write_rds(top_words, "death_row_app/top_words.rds")

```
Which race used the most negative words
```{r}

race_sentiment_tbl <- clean_data %>% 
  mutate(offender_race = case_when(offender_race == "Histpanic" ~ "Hispanic",
                                   TRUE ~ offender_race)) %>% 
  group_by(offender_race) %>% 
  mutate(race_total = n()) %>% 
  ungroup() %>%
  inner_join(get_sentiments("bing")) %>% 
  count(offender_race, sentiment, race_total) %>% 
  mutate(percent = n / race_total) %>%
  #filter(sentiment %in% c("negative","positive")) %>%
  arrange(percent) %>% 
  mutate(percent = percent*100)

write_rds(race_sentiment_tbl, "death_row_app/race_sentiment_tbl.rds")


```
Using Afinn to get the -2 to 2 distribution
```{r}
# word_afinn <- word_counts %>% 
#   inner_join(get_sentiments("afinn")) %>% 
#   #count(word, full_name, sort = TRUE) %>% 
#   count(full_name, score, total_words) %>%
#   ungroup() %>%
#   # Make a new percent column with mutate 
#   #mutate(percent = n/total_words) %>%
#   right_join(add_later, by = "full_name") %>% 
#   #filter(sentiment == "anger") %>% 
#   group_by(full_name) %>% 
#   mutate(contribution = score * n / sum(n)) %>% 
#   ggplot(aes(x = execution, y = score)) +
#     geom_boxplot()
# 
# word_afinn
```

As time passes - can allow break down by race
```{r}
library(lubridate)

sentiment_by_time <- clean_data %>%
  #right_join(add_later, by = "full_name") %>% 
  #filter(offender_race == "Black") %>% 
  mutate(date = floor_date(date, unit = "2 months")) %>%
  group_by(date) %>% 
  mutate(total_words = n()) %>% 
  ungroup() %>%
  inner_join(get_sentiments("bing")) 

write_rds(sentiment_by_time, "death_row_app/sentiment_by_time.rds")

  
```

With age 
```{r}
by_age <- sentiment_by_time %>% 
  count(age, sentiment, total_words) %>%
  ungroup() %>%  
  mutate(percent = n / total_words) %>% 
  ggplot(aes(age, percent, color = sentiment)) +
  #geom_boxplot()
  geom_line(size = 1.5)

by_age
  
```



Trying to get a boxplot - WOULD BE BETTER W AFINN
```{r}
sentiment_counts <- clean_data %>% 
  left_join(totals, by = "full_name") %>% 
  inner_join(get_sentiments("nrc")) %>% 
  filter(sentiment == "positive") %>%
  mutate(date = floor_date(date, unit = "12 months")) %>% 
  count(full_name, date, total_words) %>%
  ungroup() %>%
  mutate(percent = n / total_words) %>%
  mutate(date = ymd(date)) %>% 
  mutate(year = as.numeric(format(date,'%Y'))) %>% 
  ggplot(aes(x = as.factor(year), y = percent)) +
  geom_boxplot()
  

sentiment_counts
  
  

```

